--------------------------------------
Running PBS prologue script
--------------------------------------
User and Job Data:
--------------------------------------
Job ID:    1063820.smic3
Username:  coltonb
Group:     Users
Date:      02-Apr-2024 14:08
Node:      smic381 (23147)
--------------------------------------
PBS has allocated the following nodes:

smic381

A total of 28 processors on 1 nodes allocated
---------------------------------------------
Check nodes and clean them of stray processes
---------------------------------------------
Checking node smic381 14:08:55 
Done clearing all the allocated nodes
------------------------------------------------------
Concluding PBS prologue script - 02-Apr-2024 14:08:55
------------------------------------------------------
Loading mvapich2/2.3.3/intel-19.0.5
  Loading requirement: intel/19.0.5
JOBS_PER_NODE=1
/ddnA/work/coltonb/Multivariable_Data_Struct/Pillar_Lattice_Copies/run_sim.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import jcmwave,time,imp,shutil,os
Wavelength: 6200
Traceback (most recent call last):
  File "/home/coltonb/JCMsuite_5.2.4/ThirdPartySupport/Python/jcmwave/__private/jcmt2jcm_from_string.py", line 92, in jcmt2jcm_from_string
    try: (jcm, jcm_lines)=exec_jcmpyo(jcmpyo, copy.deepcopy(keys))
  File "/home/coltonb/JCMsuite_5.2.4/ThirdPartySupport/Python/jcmwave/__private/jcmt2jcm_from_string.py", line 219, in exec_jcmpyo
    exec(jcmpyo,globals(),jcmNameSpaceL)
  File "<jcmpy>", line 4, in <module>
KeyError: 'n_1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ddnA/work/coltonb/Multivariable_Data_Struct/Pillar_Lattice_Copies/run_sim.py", line 71, in <module>
    jcmwave.jcmt2jcm('./sources.jcmt', keys)
  File "/home/coltonb/JCMsuite_5.2.4/ThirdPartySupport/Python/jcmwave/jcmt2jcm.py", line 87, in jcmt2jcm
    except Exception as ex: raise ex
  File "/home/coltonb/JCMsuite_5.2.4/ThirdPartySupport/Python/jcmwave/jcmt2jcm.py", line 85, in jcmt2jcm
    jcmt_filetag=__jcmt2jcm(jcmt_file, keys, outputfile)
  File "/home/coltonb/JCMsuite_5.2.4/ThirdPartySupport/Python/jcmwave/jcmt2jcm.py", line 128, in __jcmt2jcm
    [jcm,backtrace]=__private.jcmt2jcm_from_string(jcmt, keys, jcmt_file)
  File "/home/coltonb/JCMsuite_5.2.4/ThirdPartySupport/Python/jcmwave/__private/jcmt2jcm_from_string.py", line 103, in jcmt2jcm_from_string
    raise Exception(error_message(jcmt_file, None, (line, None), jcmt_orig, msg))
Exception: 
  File "sources.jcmt", line: 3
    k_total = 2*math.pi*keys['n_1'].real/keys['vacuum_wavelength']
'n_1'
------------------------------------------------------
Running PBS epilogue script    - 02-Apr-2024 14:08:58
------------------------------------------------------
Checking node smic381 (MS)
Checking node smic381 ; cleared cache ; ok
------------------------------------------------------
Concluding PBS epilogue script - 02-Apr-2024 14:09:00
------------------------------------------------------
Exit Status:     1
Job ID:          1063820.smic3
Username:        coltonb
Group:           Users
Job Name:        Pillar_Lattice_Rough_Spiral
Session Id:      23146
Resource Limits: ncpus=1,neednodes=1:ppn=28,nodes=1:ppn=28,walltime=15:00:00
Resources Used:  cput=00:00:00,mem=0kb,vmem=0kb,walltime=00:00:05
Queue Used:      bigmem
Account String:  hpc_mcpeak12
Node:            smic381
Process id:      23904
------------------------------------------------------
